fix: 'unused' variable.
This is weird - normal devShell cmake build doesn't complain,
but `nix build .#tpcpp` does.

Here's the error message:
    > /build/pz08zrxh3x9b0drmz624g6a3gmaa59db-source/test/tpcpp-object/TestObjectUnary.cpp:11:8: error: variable 'expectionThrown' set but not used [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wunused-but-set-variable-Werror=unused-but-set-variable8;;]
    >    11 |   bool expectionThrown = false;
    >       |        ^~~~~~~~~~~~~~~

To suppress it, I just added an if clause that uses the offending variable.